/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package squidpony.epigon.tool;

import java.awt.event.ActionEvent;

/**
 *
 * @author Eben Howard
 */
public class GroupingPanel extends javax.swing.JPanel {

    /**
     * Creates new form GroupingPanel
     */
    public GroupingPanel() {
        initComponents();
    }

    private void doButtonAction(ActionEvent event) {
        Integer current = 0;
        try {
            current = Integer.parseInt(quantityText.getText());
        } catch (NumberFormatException nfe) {
            // Mute issue, change value to 0
        }
        switch (event.getActionCommand()) {
            case "plussOne":
                current += 1;
                break;
            case "plusTen":
                current += 10;
                break;
            case "multiplyTen":
                current *= 10;
                break;
        }
        quantityText.setText(current.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        quantityText = new javax.swing.JTextField();
        plusOneButton = new javax.swing.JButton();
        plusTenButton = new javax.swing.JButton();
        multiplyTenButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        quantityText.setText("0");
        quantityText.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        add(quantityText, gridBagConstraints);

        plusOneButton.setText("+1");
        add(plusOneButton, new java.awt.GridBagConstraints());

        plusTenButton.setText("+10");
        add(plusTenButton, new java.awt.GridBagConstraints());

        multiplyTenButton.setText("x10");
        add(multiplyTenButton, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton multiplyTenButton;
    private javax.swing.JButton plusOneButton;
    private javax.swing.JButton plusTenButton;
    public javax.swing.JTextField quantityText;
    // End of variables declaration//GEN-END:variables
}
