/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package squidpony.editor.iframes;

import squidpony.data.DataMaster;
import squidpony.editor.DataEditor;

/**
 *
 * @author Eben Howard - http://squidpony.com - howard@squidpony.com
 */
public class ConditionBlueprintIFrame extends javax.swing.JInternalFrame implements DataEditor {

    DataMaster master;

    /**
     * Creates new form ConditionBlueprintIFrame
     */
    public ConditionBlueprintIFrame() {
        initComponents();
    }

    @Override
    public void setDataMaster(DataMaster master) {
        this.master = master;
    }

    @Override
    public void loadData() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        parentComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        dataComboBox = new javax.swing.JComboBox();
        epiDataPanel = new squidpony.editor.iframes.EpiDataPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        statPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        skillList = new javax.swing.JList();
        skillListAddButton = new javax.swing.JButton();
        skillListRemoveButton = new javax.swing.JButton();
        skillPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        skillList1 = new javax.swing.JList();
        skillListAddButton1 = new javax.swing.JButton();
        skillListRemoveButton1 = new javax.swing.JButton();
        elementResistancePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        skillList2 = new javax.swing.JList();
        elementResistanceAddButton = new javax.swing.JButton();
        elementalResistanceRemoveButton = new javax.swing.JButton();
        movementPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        skillList3 = new javax.swing.JList();
        movementAddButton = new javax.swing.JButton();
        movementRemoveButton = new javax.swing.JButton();
        abilityPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        skillList4 = new javax.swing.JList();
        abilityAddButton = new javax.swing.JButton();
        abilityRemoveButton = new javax.swing.JButton();
        maxEnergyPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        skillList5 = new javax.swing.JList();
        maxEnergyAddButton = new javax.swing.JButton();
        maxEnergyRemoveButton = new javax.swing.JButton();
        energyChangePanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        skillList6 = new javax.swing.JList();
        energyChangeAddButton = new javax.swing.JButton();
        energyChangeRemoveButton = new javax.swing.JButton();
        emitPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        skillList7 = new javax.swing.JList();
        emitAddButton = new javax.swing.JButton();
        emitRemoveButton = new javax.swing.JButton();
        wearOffPanel = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        skillList8 = new javax.swing.JList();
        wearOffAddButton = new javax.swing.JButton();
        wearOffRemoveButton = new javax.swing.JButton();
        cancelPanel = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        skillList9 = new javax.swing.JList();
        cancelAddButton = new javax.swing.JButton();
        cancelRemoveButton = new javax.swing.JButton();
        conflictPanel = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        skillList10 = new javax.swing.JList();
        conflictAddButton = new javax.swing.JButton();
        conflictRemoveButton = new javax.swing.JButton();
        suppressPanel = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        skillList11 = new javax.swing.JList();
        suppressAddButton = new javax.swing.JButton();
        suppressRemoveButton = new javax.swing.JButton();
        durationSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        periodField = new javax.swing.JTextField();
        periodSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        elementComboBox = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Condition Blueprints");

        parentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));

        jLabel1.setText("Parent:");

        dataComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "New Condition" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parentComboBox, 0, 0, Short.MAX_VALUE))
                    .addComponent(epiDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(parentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epiDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jLabel3.setText("Duration:");

        durationField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        durationField.setText("50");
        durationField.setToolTipText("");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(skillList);

        skillListAddButton.setText("Add");

        skillListRemoveButton.setText("Remove");

        javax.swing.GroupLayout statPanelLayout = new javax.swing.GroupLayout(statPanel);
        statPanel.setLayout(statPanelLayout);
        statPanelLayout.setHorizontalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(statPanelLayout.createSequentialGroup()
                        .addComponent(skillListAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(skillListRemoveButton)
                        .addContainerGap())))
        );
        statPanelLayout.setVerticalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skillListAddButton)
                    .addComponent(skillListRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stat", statPanel);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(skillList1);

        skillListAddButton1.setText("Add");

        skillListRemoveButton1.setText("Remove");

        javax.swing.GroupLayout skillPanelLayout = new javax.swing.GroupLayout(skillPanel);
        skillPanel.setLayout(skillPanelLayout);
        skillPanelLayout.setHorizontalGroup(
            skillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(skillPanelLayout.createSequentialGroup()
                        .addComponent(skillListAddButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(skillListRemoveButton1)
                        .addContainerGap())))
        );
        skillPanelLayout.setVerticalGroup(
            skillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skillListAddButton1)
                    .addComponent(skillListRemoveButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Skill", skillPanel);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(skillList2);

        elementResistanceAddButton.setText("Add");

        elementalResistanceRemoveButton.setText("Remove");

        javax.swing.GroupLayout elementResistancePanelLayout = new javax.swing.GroupLayout(elementResistancePanel);
        elementResistancePanel.setLayout(elementResistancePanelLayout);
        elementResistancePanelLayout.setHorizontalGroup(
            elementResistancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elementResistancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(elementResistancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(elementResistancePanelLayout.createSequentialGroup()
                        .addComponent(elementResistanceAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(elementalResistanceRemoveButton)
                        .addContainerGap())))
        );
        elementResistancePanelLayout.setVerticalGroup(
            elementResistancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elementResistancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(elementResistancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementResistanceAddButton)
                    .addComponent(elementalResistanceRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Element Resist", elementResistancePanel);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(skillList3);

        movementAddButton.setText("Add");

        movementRemoveButton.setText("Remove");

        javax.swing.GroupLayout movementPanelLayout = new javax.swing.GroupLayout(movementPanel);
        movementPanel.setLayout(movementPanelLayout);
        movementPanelLayout.setHorizontalGroup(
            movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(movementPanelLayout.createSequentialGroup()
                        .addComponent(movementAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(movementRemoveButton)
                        .addContainerGap())))
        );
        movementPanelLayout.setVerticalGroup(
            movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movementAddButton)
                    .addComponent(movementRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Movement", movementPanel);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(skillList4);

        abilityAddButton.setText("Add");

        abilityRemoveButton.setText("Remove");

        javax.swing.GroupLayout abilityPanelLayout = new javax.swing.GroupLayout(abilityPanel);
        abilityPanel.setLayout(abilityPanelLayout);
        abilityPanelLayout.setHorizontalGroup(
            abilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(abilityPanelLayout.createSequentialGroup()
                        .addComponent(abilityAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(abilityRemoveButton)
                        .addContainerGap())))
        );
        abilityPanelLayout.setVerticalGroup(
            abilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abilityAddButton)
                    .addComponent(abilityRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ability", abilityPanel);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(skillList5);

        maxEnergyAddButton.setText("Add");

        maxEnergyRemoveButton.setText("Remove");

        javax.swing.GroupLayout maxEnergyPanelLayout = new javax.swing.GroupLayout(maxEnergyPanel);
        maxEnergyPanel.setLayout(maxEnergyPanelLayout);
        maxEnergyPanelLayout.setHorizontalGroup(
            maxEnergyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxEnergyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxEnergyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(maxEnergyPanelLayout.createSequentialGroup()
                        .addComponent(maxEnergyAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(maxEnergyRemoveButton)
                        .addContainerGap())))
        );
        maxEnergyPanelLayout.setVerticalGroup(
            maxEnergyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxEnergyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(maxEnergyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxEnergyAddButton)
                    .addComponent(maxEnergyRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Max Energy", maxEnergyPanel);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList6.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(skillList6);

        energyChangeAddButton.setText("Add");

        energyChangeRemoveButton.setText("Remove");

        javax.swing.GroupLayout energyChangePanelLayout = new javax.swing.GroupLayout(energyChangePanel);
        energyChangePanel.setLayout(energyChangePanelLayout);
        energyChangePanelLayout.setHorizontalGroup(
            energyChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(energyChangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(energyChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(energyChangePanelLayout.createSequentialGroup()
                        .addComponent(energyChangeAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(energyChangeRemoveButton)
                        .addContainerGap())))
        );
        energyChangePanelLayout.setVerticalGroup(
            energyChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(energyChangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(energyChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(energyChangeAddButton)
                    .addComponent(energyChangeRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Energy Change", energyChangePanel);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList7.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(skillList7);

        emitAddButton.setText("Add");

        emitRemoveButton.setText("Remove");

        javax.swing.GroupLayout emitPanelLayout = new javax.swing.GroupLayout(emitPanel);
        emitPanel.setLayout(emitPanelLayout);
        emitPanelLayout.setHorizontalGroup(
            emitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(emitPanelLayout.createSequentialGroup()
                        .addComponent(emitAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(emitRemoveButton)
                        .addContainerGap())))
        );
        emitPanelLayout.setVerticalGroup(
            emitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(emitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emitAddButton)
                    .addComponent(emitRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Emit", emitPanel);

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList8.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(skillList8);

        wearOffAddButton.setText("Add");

        wearOffRemoveButton.setText("Remove");

        javax.swing.GroupLayout wearOffPanelLayout = new javax.swing.GroupLayout(wearOffPanel);
        wearOffPanel.setLayout(wearOffPanelLayout);
        wearOffPanelLayout.setHorizontalGroup(
            wearOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wearOffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wearOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addGroup(wearOffPanelLayout.createSequentialGroup()
                        .addComponent(wearOffAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(wearOffRemoveButton)
                        .addContainerGap())))
        );
        wearOffPanelLayout.setVerticalGroup(
            wearOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wearOffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wearOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wearOffAddButton)
                    .addComponent(wearOffRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Wear Off", wearOffPanel);

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList9.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(skillList9);

        cancelAddButton.setText("Add");

        cancelRemoveButton.setText("Remove");

        javax.swing.GroupLayout cancelPanelLayout = new javax.swing.GroupLayout(cancelPanel);
        cancelPanel.setLayout(cancelPanelLayout);
        cancelPanelLayout.setHorizontalGroup(
            cancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10)
                    .addGroup(cancelPanelLayout.createSequentialGroup()
                        .addComponent(cancelAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(cancelRemoveButton)
                        .addContainerGap())))
        );
        cancelPanelLayout.setVerticalGroup(
            cancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAddButton)
                    .addComponent(cancelRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cancel", cancelPanel);

        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList10.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(skillList10);

        conflictAddButton.setText("Add");

        conflictRemoveButton.setText("Remove");

        javax.swing.GroupLayout conflictPanelLayout = new javax.swing.GroupLayout(conflictPanel);
        conflictPanel.setLayout(conflictPanelLayout);
        conflictPanelLayout.setHorizontalGroup(
            conflictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conflictPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conflictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addGroup(conflictPanelLayout.createSequentialGroup()
                        .addComponent(conflictAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(conflictRemoveButton)
                        .addContainerGap())))
        );
        conflictPanelLayout.setVerticalGroup(
            conflictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conflictPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(conflictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conflictAddButton)
                    .addComponent(conflictRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Conflict", conflictPanel);

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        skillList11.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "None" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(skillList11);

        suppressAddButton.setText("Add");

        suppressRemoveButton.setText("Remove");

        javax.swing.GroupLayout suppressPanelLayout = new javax.swing.GroupLayout(suppressPanel);
        suppressPanel.setLayout(suppressPanelLayout);
        suppressPanelLayout.setHorizontalGroup(
            suppressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suppressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12)
                    .addGroup(suppressPanelLayout.createSequentialGroup()
                        .addComponent(suppressAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(suppressRemoveButton)
                        .addContainerGap())))
        );
        suppressPanelLayout.setVerticalGroup(
            suppressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suppressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppressAddButton)
                    .addComponent(suppressRemoveButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Suppress", suppressPanel);

        jLabel2.setText("Element:");

        periodField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        periodField.setText("5");
        periodField.setToolTipText("");

        periodSlider.setMaximum(20);
        periodSlider.setValue(5);

        jLabel4.setText("Period:");

        elementComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(elementComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(durationSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(periodSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(durationField)
                            .addComponent(periodField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {durationSlider, elementComboBox, periodSlider});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(elementComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(durationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(periodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(periodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abilityAddButton;
    private javax.swing.JPanel abilityPanel;
    private javax.swing.JButton abilityRemoveButton;
    private javax.swing.JButton cancelAddButton;
    private javax.swing.JPanel cancelPanel;
    private javax.swing.JButton cancelRemoveButton;
    private javax.swing.JButton conflictAddButton;
    private javax.swing.JPanel conflictPanel;
    private javax.swing.JButton conflictRemoveButton;
    public javax.swing.JComboBox dataComboBox;
    private javax.swing.JTextField durationField;
    private javax.swing.JSlider durationSlider;
    private javax.swing.JComboBox elementComboBox;
    private javax.swing.JButton elementResistanceAddButton;
    private javax.swing.JPanel elementResistancePanel;
    private javax.swing.JButton elementalResistanceRemoveButton;
    private javax.swing.JButton emitAddButton;
    private javax.swing.JPanel emitPanel;
    private javax.swing.JButton emitRemoveButton;
    private javax.swing.JButton energyChangeAddButton;
    private javax.swing.JPanel energyChangePanel;
    private javax.swing.JButton energyChangeRemoveButton;
    private squidpony.editor.iframes.EpiDataPanel epiDataPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton maxEnergyAddButton;
    private javax.swing.JPanel maxEnergyPanel;
    private javax.swing.JButton maxEnergyRemoveButton;
    private javax.swing.JButton movementAddButton;
    private javax.swing.JPanel movementPanel;
    private javax.swing.JButton movementRemoveButton;
    private javax.swing.JComboBox parentComboBox;
    private javax.swing.JTextField periodField;
    private javax.swing.JSlider periodSlider;
    private javax.swing.JList skillList;
    private javax.swing.JList skillList1;
    private javax.swing.JList skillList10;
    private javax.swing.JList skillList11;
    private javax.swing.JList skillList2;
    private javax.swing.JList skillList3;
    private javax.swing.JList skillList4;
    private javax.swing.JList skillList5;
    private javax.swing.JList skillList6;
    private javax.swing.JList skillList7;
    private javax.swing.JList skillList8;
    private javax.swing.JList skillList9;
    private javax.swing.JButton skillListAddButton;
    private javax.swing.JButton skillListAddButton1;
    private javax.swing.JButton skillListRemoveButton;
    private javax.swing.JButton skillListRemoveButton1;
    private javax.swing.JPanel skillPanel;
    private javax.swing.JPanel statPanel;
    private javax.swing.JButton suppressAddButton;
    private javax.swing.JPanel suppressPanel;
    private javax.swing.JButton suppressRemoveButton;
    private javax.swing.JButton wearOffAddButton;
    private javax.swing.JPanel wearOffPanel;
    private javax.swing.JButton wearOffRemoveButton;
    // End of variables declaration//GEN-END:variables
}
