package squidpony.editor.iframes;

import squidpony.squidcolor.SColor;
import squidpony.squidcolor.SColorFactory;

/**
 * A panel containing the common data for all Epigon objects.
 *
 * @author Eben Howard - http://squidpony.com - howard@squidpony.com
 */
public class EpiDataPanel extends javax.swing.JPanel {

    public EpiDataPanel() {
        initComponents();
    }

    public SColor getDataColor() {
        if (colorPanel.isVisible()) {
            return new SColor(colorPanel.getBackground());
        } else {
            return null;
        }
    }

    public void setDataColor(SColor color) {
        if (color == null) {
            colorPanel.setBackground(color);
            colorPanel.setVisible(false);
            removeColorButton.setVisible(false);
        } else {
            colorPanel.setBackground(color);
            colorPanel.setVisible(true);
            removeColorButton.setVisible(true);
        }
    }

    public void setParentColor(SColor color) {
        parentColorPane.setBackground(color);
    }

    public String getDescription() {
        return descriptionArea.getText();
    }

    public void setDescriptionArea(String description) {
        descriptionArea.setText(description);
    }

    public String getDataName() {
        return nameField.getText();
    }

    public void setDataName(String name) {
        nameField.setText(name);
    }

    public String getNotes() {
        return notesArea.getText();
    }

    public void setNote(String notes) {
        notesArea.setText(notes);
    }

    public String getPluralName() {
        return pluralField.getText();
    }

    public void setPluralName(String plural) {
        pluralField.setText(plural);
    }

    public String getInternalName() {
        return internalNameField.getText();
    }

    public void setInternalName(String name) {
        internalNameField.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        internalNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        colorButton = new javax.swing.JButton();
        colorPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pluralField = new javax.swing.JTextField();
        saveChangesButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        removeColorButton = new javax.swing.JButton();
        deleteEntryButton = new javax.swing.JButton();
        parentColorPane = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(315, 440));
        setPreferredSize(new java.awt.Dimension(315, 440));

        jLabel1.setText("Name:");

        nameField.setToolTipText("<html>In game name.<br>This name does not need to be unique.</html>");

        jLabel2.setText("Internal:");

        internalNameField.setToolTipText("<html>Behind the scenes name.<br>This name must be unique.</html>");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descriptionArea.setLineWrap(true);
        descriptionArea.setRows(3);
        descriptionArea.setTabSize(4);
        descriptionArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descriptionArea);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        notesArea.setLineWrap(true);
        notesArea.setRows(3);
        notesArea.setTabSize(4);
        notesArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(notesArea);

        colorButton.setText("Color");
        colorButton.setToolTipText("The display color of the object.");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        colorPanel.setBackground(new java.awt.Color(160, 79, 0));
        colorPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        colorPanel.setToolTipText("Object's Color");
        colorPanel.setMinimumSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel3.setText("Plural:");

        pluralField.setToolTipText("<html>The plural form of the in game name.<br>If this is blank than the Name will be used with an 's' appended.</html>");

        saveChangesButton.setText("Save Changes");
        saveChangesButton.setToolTipText("Saves this object to the DataMaster.");

        removeColorButton.setText("Remove Color");
        removeColorButton.setToolTipText("<html>Remove the Color from this object.<br>In game the object will then use its parent's color.</html>");
        removeColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeColorButtonActionPerformed(evt);
            }
        });

        deleteEntryButton.setText("Delete Entry");
        deleteEntryButton.setToolTipText("<html>This completely removes the current data object.<br>If this object was the parent of other objects, they will be redirected to have this object's parent as theirs.</html>");

        parentColorPane.setBackground(null);
        parentColorPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        parentColorPane.setToolTipText("Parent Color");
        parentColorPane.setMinimumSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout parentColorPaneLayout = new javax.swing.GroupLayout(parentColorPane);
        parentColorPane.setLayout(parentColorPaneLayout);
        parentColorPaneLayout.setHorizontalGroup(
            parentColorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        parentColorPaneLayout.setVerticalGroup(
            parentColorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField)
                            .addComponent(internalNameField)
                            .addComponent(pluralField)))
                    .addComponent(saveChangesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(parentColorPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(removeColorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(deleteEntryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(internalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pluralField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorButton)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeColorButton)
                    .addComponent(parentColorPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveChangesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteEntryButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        setDataColor(SColorFactory.showSColorChooser(this.getParent()));
    }//GEN-LAST:event_colorButtonActionPerformed

    private void removeColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeColorButtonActionPerformed
        setDataColor(null);
    }//GEN-LAST:event_removeColorButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorButton;
    private javax.swing.JPanel colorPanel;
    public javax.swing.JButton deleteEntryButton;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JTextField internalNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JPanel parentColorPane;
    private javax.swing.JTextField pluralField;
    private javax.swing.JButton removeColorButton;
    public javax.swing.JButton saveChangesButton;
    // End of variables declaration//GEN-END:variables
}
